language: node_js
node_js:
- "10"
script:
  - npm run build
after_success: |
  if [ -n "$GITHUB_API_TOKEN" ]; then
  cd "$TRAVIS_BUILD_DIR"
  make web
  cd web
  git init
  git checkout -b gh-pages
  git add .
    git -c user.name = 'travis' -c user.email = 'travis' commit -m 'init'
  git push -f -q https://yurikoex:$GITHUB_API_KEY@github.com/yurikoex/idle-gh-pages gh-pages &2>/dev/null
  cd "$TRAVIS_BUILD_DIR"
  fi